### ISSUE TITLE
GET /console/lab/data_reports/:id 少了 figure_ids

### ISSUE THREAD

**Issue by chihhhhhao** [watchout-tw/core-documentation#4]
我已經加上去了。不過請 @wesley100002001 檢查一下，目前 core-docs 內容有沒有與《中控室》介面不一致的地方。

**Comment by chihhhhhao** [comment]
總共三個 commits b7024375a33ced8da43b3874f9fae5636f9f0024 75909c52c31930e8030c7bb0cfc1cd208ea55063 044286f102d5aafe0c909617d684b2463238b73a

**Comment by wesley100002001** [comment]
Checked. Should be okay.
