### ISSUE TITLE
[Review] GET /ask/games/:slug

### ISSUE THREAD

**Issue by charlieworld** [watchout-tw/core-documentation#8]
/ask/games/:slug  的 matches 現在是為

matches: [
    *matchObject*
  ]

而根據 matches 的 docs : https://docs.core.watchout.tw/ask/matches

1. Match 的物件資料整個塞進來是否會太龐大？
2. Match 裡面也有包含 **展開的** game 物件 ， 這看起來不太合理... ( 這樣變成 Game 中有 Game ...)

**Comment by chihhhhhao** [comment]
1. 有兩個選項
* 用完整的matchObject格式，成本是core SQL比較複雜，資料傳輸量比較大
* 用精簡的matchObject格式，成本是要負擔可能的前端介面更動、api spec更新，又會回到完整的matchObject格式

2. 在`GET /ask/games/:slug`裡的matchObject就不要把game_id展開成gameObject，維持game_id好了。

**Comment by wesley100002001** [comment]
補充 1. 的部份，不知道對不對，但想像中實際上一個 Game 會有的 Matches 應該不會太多，因為會對應到實體活動，也許都在 10 筆之內？應該不會出現有百筆的 Matches XD
2. Totally agree :D

**Comment by charlieworld** [comment]
看起來共識是 matchObject 的 event 要展開，而 game 不用展開，維持 game_id ， 對嗎？
