### ISSUE TITLE
[Review]  GET /console/ask/questions

### ISSUE THREAD

**Issue by charlieworld** [watchout-tw/core-documentation#9]
建議 跟 GET /ask/questions  (without token)的規格一致 (這樣我就不用改query了～)

所以一樣會吐 persona_speech_targets , push

**Comment by charlieworld** [comment]
@wesley100002001  @chihaoyo

**Comment by chihhhhhao** [comment]
好的！已按照建議修改 https://github.com/watchout-tw/core-documentation/commit/1cc051631e7f5d494489a87f3f05e9e43bdb7226
